name: Build & Deploy Storefront

on:
  push:
    paths:
      - "storefront/**"
      - ".github/workflows/storefront.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myregistry/storefront ./storefront

      - name: Push image
        run: echo "push to your registry..."